# Generated by Django 5.1.1 on 2025-04-20 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0001_initial (1)'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=66, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=66)),
                ('user_keys', models.JSONField(default=list)),
                ('user_names', models.JSONField(default=list)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='mp.file')),
            ],
            options={
                'unique_together': {('file', 'user_id')},
            },
        ),
        migrations.DeleteModel(
            name='FileMetadata',
        ),
    ]
